version: '3.8'

services:
   swarm-manager:
    image: ghcr.io/affell/swarm-manager:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.swarm-manager.rule=Host(`swarm.sys.affell.fr`)
        - traefik.http.routers.swarm-manager.tls.certresolver=resolver
        - traefik.http.routers.swarm-manager.entrypoints=websecure
        - traefik.http.routers.swarm-manager.middlewares=whitelist
        - traefik.http.services.swarm-manager.loadbalancer.server.port=5000
        - "traefik.http.routers.swarm-manager.middlewares=websocket-headers"
        - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.X-Forwarded-Ssl=on"
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - public

networks:
  default:
    driver: overlay